s=set ()
print(type(s))
s_form_list = set([1,2,3,4,5,6,9])
print(">>>set of S_form_list",s_form_list)
s.add(1)
s.add(3)
s.add(8)
s.add(6)
print(">>> set of S is:",s)
s1=s.union([1,12,45])
print(">>>After union the set s and {1,12,45} is :",s1)
s2=s.intersection({1,4,5,7,8})
print(">>>After intersection with the set s and {1,4,5,7,8} is :",s2)
print(">>length of the set is :",len(s))
print (">>> min and max elements of this set s is :",min(s) ,"and" ,max(s))
print(">>>: check this set s1 and s2 are disjoint :",s.isdisjoint(s1))
s.remove(1)
print(">>> After remove the elemts in s",s)